version: '3.9'

services:
  redis:
    image: redis
    ports:
      - '6379:6379'
    environment:
      - REDIS_PASSWORD=123456
    command: redis-server --requirepass 123456
    volumes:
      - redis-data:/data
    restart: always

volumes:
  redis-data:
